### ISSUE TITLE
2FA Authenticator (v0.04) gets stuck on loading... even with default apps

### ISSUE THREAD

**Issue by zx85** [andrewgoz/Authentiwatch#10]
I'm a new user of Bangle.js but I've not been able to get the 2FA Authenticator app to install on my device.

It's just giving me "Loading..." - as per this photo: 
![image](https://user-images.githubusercontent.com/708096/147860442-57c38d90-4df7-4404-802d-52be2ddd88da.png)

That's after I've followed the instructions in "_About -> Install default apps_" and even removed as many of the apps as I could find - as per the other open post that mentioned crypto.js ...

There's odd stuff going on with the IDE as well ...
![image](https://user-images.githubusercontent.com/708096/147860400-aea99178-d34d-4e70-804e-440377cc8e3f.png)

I'm a bit clueless now.. can you help? Most other things seem to work. I have no idea what I'm doing... thanks in advance.

**Comment by andrewgoz** [comment]
I suspect this is going to be the same thing as for #7

**Comment by zx85** [comment]
Thanks, Andrew. Oddly it works in the emulator on the main site - I guess there's something odd going on with the (latest?) firmware.

Is there anything I can do to assist with diagnosis?

j

**Comment by andrewgoz** [comment]
All I can think of is to connect to the watch using the IDE, then try running my app on the watch and see if any interesting messages appear in the console.

**Comment by andrewgoz** [comment]
I think this should be fixed once the AppLoader web page is updated.

**Comment by zx85** [comment]
I've just checked and it's working like a dream now... honestly, it's an incredibly useful tool to have on my wrist in these days of heightened security - thank you for taking the time to develop it!
