### ISSUE TITLE
Uncaught Error: Module crypto not found

### ISSUE THREAD

**Issue by KTibow** [andrewgoz/Authentiwatch#7]
Just launching the app on firmware 2v11, I get this:
```
 ____                 _
|  __|___ ___ ___ _ _|_|___ ___
|  __|_ -| . |  _| | | |   | . |
|____|___|  _|_| |___|_|_|_|___|
         |_| espruino.com
 2v11 (c) 2021 G.Williams
Uncaught Error: Module crypto not found
 at line 2 col 25 in authentiwatch.app.js
const crypto=require("crypto");
```
Anything I could do to fix this?

**Comment by andrewgoz** [comment]
The crypto module is part of the firmware. I assume you have a standard firmware?

**Comment by KTibow** [comment]
As it shows in the logs, I'm running 2v11, uploaded from the Espruino IDE.

**Comment by andrewgoz** [comment]
Could you try following the instructions under [Resetting without loading any code](http://www.espruino.com/Bangle.js2#resetting-without-loading-any-code)? - the screen should look like: https://imgur.com/fJiMifN

At this point, connect to the watch via the IDE. Click on the storage icon (icon of 4 stacked discs), find my app file "authentiwatch.app.js", and click the play button (right-pointing triangle icon).

My app should load and show either "No Tokens", or a list of the tokens you've configured. If that works, then I think it means a Javascript file that loads at boot time (*.boot.js) is somehow blocking the crypto module from loading. You might have to try uninstalling apps to see which one it is.

**Comment by KTibow** [comment]
FYI I'm using the Bangle.js 1. It still gives the error that it couldn't find the crypto module. My only other `boot.js` integration is Android.

**Comment by andrewgoz** [comment]
It looks like [an AppLoader change](https://github.com/espruino/EspruinoAppLoaderCore/commit/23854083e0c3f83c649073a2d85e8079efc471d3) effectively at my request to enable full crypto module support for the JS2 might have broken things for the JS1. This will have to wait until Gordon returns from his holiday break.

**Comment by andrewgoz** [comment]
I think this should be fixed once the AppLoader web page is updated.
